# SnapAdmin Configuration
snapadmin.enabled=true
snapadmin.baseUrl=admin
snapadmin.modelsPackage=tech.ailef.snapadmin.internal.model,com.oidea

# Database Configuration (H2 In-Memory)
spring.datasource.url=jdbc:h2:mem:snapadmin;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# MyBatis-Plus Configuration
mybatis-plus.mapper.scan=tech.ailef.snapadmin.internal.mapper
mybatis-plus.global-config.db-config.id-type=auto
mybatis-plus.configuration.map-underscore-to-camel-case=true
